diary/urls.py
from django.contrib import admin
from django.conf.urls import include, url
from django.urls import path
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),

    url(r'^login/$', 
        auth_views.login, 
        {'template_name': 'registration/login.html'},
        name='login'
    ),
    url(r'^logout/$', 
        auth_views.logout, 
        {'next_page': 'home'},
        name='logout'
    ),
    url(r'^', include('note.urls')),
    
]

LOGIN_URL = 'login'
LOGOUT_URL = 'logout'
LOGIN_REDIRECT_URL = 'home'

note/urls.py
from django.conf.urls import url, include
from note import views

urlpatterns = [
    url(r'^$', views.index, name="home"),
    url(r'^class/(?P<pk>\d+)$', views.detail, name="detail"),
    url(r'^signup/$', views.signup, name="signup")
] 

note/models.py
from django.db import models
from ckeditor.fields import RichTextField
from datetime import datetime
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver

# Create your models here.

class Class(models.Model):
    name_course = models.CharField(max_length = 255)
    number = models.IntegerField()
    teacher = models.ForeignKey('UserProfile', limit_choices_to={'headline':"Teacher"}, on_delete = models.CASCADE, related_name="teacher", blank = True)
    support = models.ForeignKey('UserProfile', limit_choices_to={'headline':"Supporter"},on_delete = models.CASCADE, related_name = "supporter", blank = True)
    def __str__(self):
        return self.name_course+" "+str(self.number)
    class Meta:
        verbose_name = 'Class'
        verbose_name_plural = 'Classrooms'

class Diary(models.Model):
    author = models.ForeignKey('auth.User', on_delete = models.CASCADE)
    time = models.DateField(default = datetime.now)
    classroom = models.ForeignKey(Class, on_delete = models.CASCADE, related_name='diary')
    note_summary = RichTextField()

    def __str__(self):
        return self.classroom.name_course +" "+str(self.classroom.number) +" - "+ datetime.strftime(self.time, "%d/%m/%Y")

    class Meta:
        verbose_name = 'Diary'
        verbose_name_plural = 'Diaries'

class NotePrecise(models.Model):
    for_student = models.CharField(max_length = 255)
    diary = models.ForeignKey(Diary, on_delete = models.CASCADE, related_name='note_precise')
    note = RichTextField()

    def __str__(self):
        return self.for_student +" "+ self.diary.classroom.name_course +" "+ str(self.diary.classroom.number)
    class Meta:
        verbose_name = 'Note Precise'
        verbose_name_plural = 'Note for each Student'

HEADLINE_CHOICES = (
        ("Teacher", "Teacher"),
        ("Supporter", "Supporter"),
        ("Manager", "Manager")
    )

class UserProfile(models.Model):
    user   = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    
    headline = models.CharField(
        max_length=255, choices=HEADLINE_CHOICES, default=HEADLINE_CHOICES[0])

    def __str__(self):
        if self.user.first_name and self.user.last_name:
            return '%s %s' % (self.user.first_name, self.user.last_name)
        else:
            return self.user.username

@receiver(post_save, sender=User)
def update_user_profile(sender, instance, created, **kwargs):
    if created:
        UserProfile.objects.create(user=instance)
    instance.userprofile.save()

note/forms.py
from django import forms
from django.core.files.images import get_image_dimensions
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import *


class SignUpForm(UserCreationForm):
    
    headline = forms.ChoiceField(
        choices=HEADLINE_CHOICES, required = True)

    first_name = forms.CharField(
        max_length=30, required=False, help_text='Optional.')
    last_name = forms.CharField(
        max_length=30, required=False, help_text='Optional.')
    email = forms.EmailField(
        max_length=254, help_text='Required. Inform a valid email address.')

    class Meta:
        model = User
        fields = ('username', 'email','first_name','last_name','headline', 'password1', 'password2', )


# class UserProfileForm(forms.ModelForm):
#     class Meta:
#         model = UserProfile
#         fields = ('__all__')

note/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import *
from django.contrib.auth import login, authenticate
from .forms import SignUpForm
from django.contrib.auth.models import Permission

# Create your views here.

def index(request):
    user = request.user
    classrooms = None
    if not user.is_active:
        print("Chưa đăng nhập")
    else:
        if user.userprofile.headline == "Manager" or user.is_superuser:
            classrooms = Class.objects.all()
            print("Super")
        elif user.userprofile.headline == "Teacher":
            classrooms = user.userprofile.teacher.all()
            print("Teacher")
        elif user.userprofile.headline == "Supporter":
            classrooms = user.userprofile.supporter.all()
            print("Support")

    # classrooms = Class.objects.all()
    date_list = [d.time for d in Diary.objects.all()]
    date_list = sorted(date_list)
    context = {
        'classrooms': classrooms,
        'date_list': date_list
    }

    return render(request, "homepage.html", context = context)

def detail(request, pk):
    classroom = get_object_or_404(Class, pk = pk)
    if classroom != None:
        if request.user.userprofile.headline == "Supporter":
            notes = classroom.diary.filter(author = request.user).order_by('-time')
        else:
            notes = classroom.diary.all().order_by('-time')

    context = {
        'classroom': classroom,
        "notes" : notes,
    }
    return render(request, "detail.html", context = context)

support_permission = ['Can add diary', 'Can change diary', 'Can delete diary', 'Can add note precise', 'Can change note precise', 'Can delete note precise']

manager_permission = ['Can add diary', 'Can change diary', 'Can delete diary', 'Can add note precise', 'Can change note precise', 'Can delete note precise', 'Can add user', 'Can change user', 'Can delete user', 'Can add permission', 'Can change permission', 'Can delete permission', 'Can add class', 'Can change class', 'Can delete class', 'Can add user profile', 'Can change user profile', 'Can delete user profile']

def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save()
            user.refresh_from_db()
            user.userprofile.headline = form.cleaned_data.get("headline")
            user.is_staff = True
            user.save()
            
            headline = user.userprofile.headline
            if headline == "Supporter" or headline == "Teacher":
                for permiss in support_permission:
                    permission = Permission.objects.get(name=permiss)
                    user.user_permissions.add(permission)

            elif headline == "Manager":
                for permiss in manager_permission:
                    permission = Permission.objects.get(name=permiss)
                    user.user_permissions.add(permission)

            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('home')
    else:
        form = SignUpForm()
    return render(request, 'registration/signup.html', {'uform': form})

note/templates/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    {% include "partial/meta-data.html" %}
</head>
<body>
    {% include "partial/nav.html" %}
    {% include "detail/header.html" %} 
    {% include "detail/main.html" %} 
    {% include "partial/footer.html" %}
</body>
</html>

note/templates/detail/header.html
<div class='text-center header-container mt-5'>
    <a class="" href="/">
        <img style="width: 100px; height: 100px;" src="https://www.teerexradioteerex.com/wp-content/uploads/2016/12/calendar-icon.png">
    </a>
    <!-- <h2 class="mt-3">TechKids Diary</h2> -->
    <h3 class="font-weight-bold mt-4">{{ classroom }}</h3>
    <hr>
</div>

note/templates/detail/main.html
<div class="my-container mt-5">
    {% for note in notes %}
        <h3 class="text-primary">{{ note.time|date:'l, d-m-Y' }}</h3>
        <div class="ml-3 note mb-5">
            <div class="text-muted font-italic">
                <label class="mt-3 mb-4">
                    <i class="fas fa-user-edit"></i> {{ note.author.first_name }} {{ note.author.last_name }}
                </label>
                <!-- <label class="ml-2">
                    <i class="fas fa-graduation-cap"></i> {{ note.author.userprofile.get_headline_display }}
                </label> -->
            </div>
            <h5 class="font-weight-bold">Nhận xét chung</h5>
            <p>{{ note.note_summary|safe }}</p>
            <br>
            {% if note.note_precise.all %} 
                <h5 class="font-weight-bold">Nhận xét riêng</h5>
                {% for pre in note.note_precise.all %}
                <div class="mb-2 mt-3">

                    <i class="font-weight-light">Học viên : {{ pre.for_student }}</i>
                    <p>{{ pre.note|safe }}</p>
                </div>
                {% endfor %} 
            {% endif %}
        </div>
        <hr>
    {% endfor %}
</div>

note/templates/homepage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    {% include "partial/meta-data.html" %}
</head>
<body>
    {% include "partial/nav.html" %}
    {% include "partial/header.html" %}
    {% include "homepage/main.html" %}
    {% include "partial/footer.html" %}
</body>
</html>

note/templates/homepage/main.html
<div class="container" style="margin-top:100px;">
    <div class="row">
        <div class="col-sm-8 px-5">
            {% if classrooms == None %}
            
            <img src="https://flisebent.dk/wp-content/uploads/2017/11/preview.png" alt="" style="width: 100%">
            
            {% else %}
            {% for class in classrooms %}
            <div>
                <a href="/class/{{class.pk}}" class="mb-3">
                    <i class="fas fa-caret-right"></i>
                    {{ class }}
                </a>
                <!-- <p>{{ note.note_summary|safe|truncatewords_html:40 }}</p>
                <button class="btn btn-primary">Continue Reading</button>
                <p class="mb-4"></p>
                <small>Người viết: {{note.author.first_name}} {{note.author.last_name}} | Khóa học: {{ note.classroom.name_course }}</small> -->
            </div>
            <hr>
            {% endfor %}
            {% endif %}
        </div>
        <div class="col-sm-4">
            <div class="from-group mb-4">
                <p class="font-weight-bold">Tìm kiếm</p>
                <input class="form-control w-100" type="text" placeholder="Nhập tên lớp" name="" id="">
            </div>
            <div class="mt-4">
                <p class="font-weight-bold">Note theo ngày</p>
                <ul>
                    {% for date in date_list %}
                        <a href="">
                            <li>{{date}}</li>
                        </a>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
</div>

note/templates/partial/footer.html
<footer class="bg-dark py-2 mt-3">
    <div class=" text-center text-light">
        <p style="margin:0;">© Copyright 2018 TechKids.vn - All Rights Reserved</p>
    </div>
</footer>

note/templates/partial/header.html
<div class='text-center header-container mt-5'>
    <a class=""  href="/">
        <img style="width: 100px; height: 100px;" src="https://www.teerexradioteerex.com/wp-content/uploads/2016/12/calendar-icon.png">
    </a>
    <h2 class="mt-3">TechKids Diary</h2>
    <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit.</p>
    <hr>
</div>

note/templates/partial/meta-data.html
<link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">


<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4"
  crossorigin="anonymous">

<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt"
  crossorigin="anonymous">

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
  crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js" integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ"
  crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm"
  crossorigin="anonymous"></script>

<title>Diary</title>
<link rel="stylesheet" href="../static/css/body.css">

note/templates/partial/nav.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark sticky-top">
    <a class="navbar-brand" href="/">Techkids Diary</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false"
        aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a class="nav-link" href="/">Home
                </a>
            </li>
            {% if user.is_staff %}
            <li class="nav-item">
                <a class="nav-link" href="/admin">Admin Page
                </a>
            </li>
            {% endif %}
            <!-- <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Nhật ký theo khóa học
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                    <a class="dropdown-item" href="#">C4E</a>
                    <a class="dropdown-item" href="#">CI</a>
                </div>
            </li> -->
        </ul>
        <ul class="navbar-nav">
        {% if user.is_authenticated %}
            <li class="nav-item mr-2">
                <a class="nav-link">Xin chào, {{ user.username }}</a>
            </li>
            <li class="nav-item mr-2">
                <a class="nav-link" href="/logout">Logout</a>
            </li>
        {% else %}
            <li class="nav-item mr-2">
                <a class="nav-link" href="/login">Login</a>
            </li>
            <li class="mr-2 nav-item">
                <a class="nav-link" href="/signup">Signup</a>
            </li>
        {% endif %}
        </ul>
    </div>
</nav>